### ISSUE TITLE
Ícone Home enviando para outro site

### ISSUE THREAD

**Issue by Gatasso** [Mathlps/Aquamarine_Ext#1]
Ao clicar no Ícone da Home, o direcionamento está para outro site

**Comment by PaulingCavalcante** [comment]
Problema resolvido.

O href da imagem da navbar e o home da navbar estava:

<pre>href="/"</pre>

Dessa forma, ele leva para o index da página, que no github pages, é o index da pág do @Mathlps.
Esse erro não aconteceria se o site estivesse hospedado em algum outro site com url e rota unica para o site.

Mas por ora, para resolver o problema, defini o href da seguinte forma:

![image](https://github.com/user-attachments/assets/9b3bf8bc-a554-4574-bc1e-1638d7ce17ef)

Assim, ele leva ao index do site do projeto, sem alterar a rota do Aquamarine no github pages.

Sugiro que o site seja hospedado na Vercel ou alguma outra ferramenta de hospedagem, pois evita possíveis problemas com rotas e URLs, além de conseguirmos gerir o domínio do site, deixando ele com uma URL própria para o projeto.
